"""Maryland depth: every county, plus named organisations with real URLs.

TRACK RECORD -- read this before trusting the field.
I have no dataset of which venues robotics teams have actually visited. Nobody
publishes one. So this file never claims "N teams went here", because that would
be invented social proof, which is worse than no proof at all. Instead each entry
carries one of four honest levels:

  hosts      This venue hosts official FIRST events, so teams are demonstrably
             there every season. Checkable on FIRST's own event list.
  programme  The organisation runs its own published youth STEM or education
             programme. Checkable on their site.
  open       The venue takes community bookings as a matter of course, but there
             is no public record of robotics teams specifically.
  unknown    No public record either way. Ask the teams near it first.

Every card tells you how to check for yourself, and the board links you to
FIRST's team search so you can ask the teams who would actually know.
"""

# label, county, region-of-state
AREAS = [
 ("Baltimore", "Baltimore City", "Central Maryland"),
 ("Towson", "Baltimore County", "Central Maryland"),
 ("Dundalk", "Baltimore County", "Central Maryland"),
 ("Owings Mills", "Baltimore County", "Central Maryland"),
 ("Catonsville", "Baltimore County", "Central Maryland"),
 ("Annapolis", "Anne Arundel County", "Central Maryland"),
 ("Glen Burnie", "Anne Arundel County", "Central Maryland"),
 ("Columbia", "Howard County", "Central Maryland"),
 ("Ellicott City", "Howard County", "Central Maryland"),
 ("Rockville", "Montgomery County", "Capital Region"),
 ("Silver Spring", "Montgomery County", "Capital Region"),
 ("Bethesda", "Montgomery County", "Capital Region"),
 ("Gaithersburg", "Montgomery County", "Capital Region"),
 ("Germantown", "Montgomery County", "Capital Region"),
 ("College Park", "Prince George's County", "Capital Region"),
 ("Bowie", "Prince George's County", "Capital Region"),
 ("Upper Marlboro", "Prince George's County", "Capital Region"),
 ("Laurel", "Prince George's County", "Capital Region"),
 ("Greenbelt", "Prince George's County", "Capital Region"),
 ("Frederick", "Frederick County", "Western Maryland"),
 ("Hagerstown", "Washington County", "Western Maryland"),
 ("Cumberland", "Allegany County", "Western Maryland"),
 ("Oakland", "Garrett County", "Western Maryland"),
 ("Westminster", "Carroll County", "Central Maryland"),
 ("Bel Air", "Harford County", "Central Maryland"),
 ("Aberdeen", "Harford County", "Central Maryland"),
 ("Elkton", "Cecil County", "Central Maryland"),
 ("Chestertown", "Kent County", "Eastern Shore"),
 ("Centreville", "Queen Anne's County", "Eastern Shore"),
 ("Easton", "Talbot County", "Eastern Shore"),
 ("Cambridge", "Dorchester County", "Eastern Shore"),
 ("Denton", "Caroline County", "Eastern Shore"),
 ("Salisbury", "Wicomico County", "Eastern Shore"),
 ("Princess Anne", "Somerset County", "Eastern Shore"),
 ("Snow Hill", "Worcester County", "Eastern Shore"),
 ("Ocean City", "Worcester County", "Eastern Shore"),
 ("Prince Frederick", "Calvert County", "Southern Maryland"),
 ("La Plata", "Charles County", "Southern Maryland"),
 ("Waldorf", "Charles County", "Southern Maryland"),
 ("Leonardtown", "St. Mary's County", "Southern Maryland"),
 ("Lexington Park", "St. Mary's County", "Southern Maryland"),
]

# name, city, county, url, venue key, track record, what they are, what to ask them for
ORGS = [
 ("FIRST Chesapeake", "Glen Burnie", "Anne Arundel County", "https://www.firstchesapeake.org", "event", "hosts",
  "The FIRST district organisation for Maryland, DC and Virginia. It runs every official FRC, FTC and FLL event in the state.",
  "Start here before anything else on this page. Their event list shows which Maryland venues host events and when, and they need volunteers at every one."),
 ("Maryland Science Center", "Baltimore", "Baltimore City", "https://www.mdsci.org", "museum", "programme",
  "Baltimore's science centre on the Inner Harbor, with a large public-programmes operation.",
  "Ask Public Programs about exhibiting on a family science weekend. Expect to supply a certificate of insurance."),
 ("Port Discovery Children's Museum", "Baltimore", "Baltimore City", "https://www.portdiscovery.org", "museum", "programme",
  "A children's museum in downtown Baltimore aimed at under-tens.",
  "Ask about their family event calendar. Bring something a six-year-old can operate, not the competition robot."),
 ("National Aquarium", "Baltimore", "Baltimore City", "https://aqua.org", "museum", "programme",
  "The Inner Harbor aquarium, which runs conservation education and volunteer programmes.",
  "Ask about their conservation education events; an underwater or sensor-themed demo fits their brief honestly."),
 ("The Maryland Zoo in Baltimore", "Baltimore", "Baltimore City", "https://www.marylandzoo.org", "museum", "programme",
  "The zoo in Druid Hill Park, with a substantial education department.",
  "Ask the education department about their family science days and summer camp programme."),
 ("B&O Railroad Museum", "Baltimore", "Baltimore City", "https://www.borail.org", "museum", "programme",
  "A railroad museum with a strong engineering-history education programme.",
  "Ask about their STEM days. Mechanisms and drivetrains are an unusually natural fit here."),
 ("Baltimore Museum of Industry", "Baltimore", "Baltimore City", "https://www.thebmi.org", "museum", "programme",
  "A museum of Baltimore's manufacturing history, with hands-on education programming.",
  "Ask about family days and their maker programming. Their audience already likes machines."),
 ("NASA Goddard Space Flight Center", "Greenbelt", "Prince George's County", "https://www.nasa.gov/goddard", "univ", "programme",
  "A major NASA centre with a visitor centre and a formal education and outreach office.",
  "Contact the Office of STEM Engagement about their events. Their monthly visitor-centre programmes take outside exhibitors."),
 ("Johns Hopkins Applied Physics Laboratory", "Laurel", "Howard County", "https://www.jhuapl.edu", "univ", "programme",
  "A large research laboratory in Laurel that runs a well-established K-12 STEM outreach programme.",
  "Ask their STEM outreach office about volunteering at their events, and about mentors for your own team."),
 ("Enoch Pratt Free Library", "Baltimore", "Baltimore City", "https://www.prattlibrary.org", "library", "programme",
  "Baltimore City's public library system and Maryland's State Library Resource Center, with branches across the city.",
  "Email the Youth Services staff at a specific branch, not the central address. Ask about summer programming in January."),
 ("Baltimore County Public Library", "Towson", "Baltimore County", "https://www.bcpl.info", "library", "programme",
  "The county system, with branches across Baltimore County and an active STEM programme.",
  "Ask about their maker and STEM programming; several branches have dedicated space for it."),
 ("Howard County Library System", "Columbia", "Howard County", "https://hclibrary.org", "library", "programme",
  "Howard County's library system, which runs a large and well-funded STEM education programme.",
  "Ask about their A+ Partnership and STEM classes. This system takes outside instructors seriously."),
 ("Anne Arundel County Public Library", "Annapolis", "Anne Arundel County", "https://www.aacpl.net", "library", "programme",
  "The county library system serving Annapolis and the surrounding area.",
  "Ask the branch's Youth Services staff about a demo slot, and about summer reading in January."),
 ("Harford County Public Library", "Bel Air", "Harford County", "https://www.hcplonline.org", "library", "programme",
  "Harford County's system, with branches across the county.",
  "Ask about STEM programming and their summer reading calendar."),
 ("Frederick County Public Libraries", "Frederick", "Frederick County", "https://www.fcpl.org", "library", "programme",
  "The Frederick County system.",
  "Ask about family programming; the main branch has the space for a driveable robot."),
 ("Carroll County Public Library", "Westminster", "Carroll County", "https://library.carr.org", "library", "programme",
  "Carroll County's library system, which runs regular STEM sessions.",
  "Ask about their STEM programming calendar and their maker offerings."),
 ("Prince George's County Memorial Library System", "Largo", "Prince George's County", "https://www.pgcmls.info", "library", "programme",
  "The county system serving Prince George's County.",
  "Ask about branch programming and about their bilingual family events."),
 ("Montgomery County Public Libraries", "Rockville", "Montgomery County", "https://www.montgomerycountymd.gov/library", "library", "programme",
  "One of the largest library systems in the state, with branches across Montgomery County.",
  "Ask a specific branch's children's or teen librarian. County-level requests get routed anyway."),
 ("Digital Harbor Foundation", "Baltimore", "Baltimore City", "https://www.digitalharbor.org", "maker", "programme",
  "A Baltimore youth technology nonprofit running a maker space and after-school programmes.",
  "Ask about volunteering with their youth programmes, and about their space for your own workshops."),
 ("Living Classrooms Foundation", "Baltimore", "Baltimore City", "https://livingclassrooms.org", "afterschool", "programme",
  "A Baltimore nonprofit running education and workforce programmes for young people.",
  "Ask about their after-school and summer programmes; they take structured volunteer-led sessions."),
 ("Maryland 4-H, University of Maryland Extension", "College Park", "Prince George's County", "https://extension.umd.edu/programs/4-h-youth-development", "fourh", "programme",
  "The statewide 4-H programme, run through county extension offices in all 23 counties and Baltimore City.",
  "Find your county's 4-H Youth Development Agent. One email replaces twenty to individual clubs."),
 ("Maryland State Fair", "Timonium", "Baltimore County", "https://www.marylandstatefair.com", "fair", "open",
  "The state fair, held at Timonium each summer.",
  "Ask the exhibits coordinator about a youth or non-profit exhibitor space. Apply in the winter for the following summer."),
 ("Maryland Food Bank", "Baltimore", "Baltimore City", "https://mdfoodbank.org", "foodbank", "programme",
  "The statewide food bank, with branches serving central Maryland and the Eastern Shore.",
  "Book a group sorting shift through their volunteer calendar. Check the minimum age for your students."),
 ("Chesapeake Bay Foundation", "Annapolis", "Anne Arundel County", "https://www.cbf.org", "parks", "programme",
  "A conservation organisation running large student education and restoration programmes across the bay.",
  "Ask about student volunteer projects; a sensor or water-quality build fits their work genuinely."),
 ("Maryland Department of Natural Resources", "Annapolis", "Anne Arundel County", "https://dnr.maryland.gov", "parks", "open",
  "The state agency running Maryland's parks and their public programming.",
  "Ask a specific state park about their event calendar; several run family science days."),
 ("Baltimore City Public Schools", "Baltimore", "Baltimore City", "https://www.baltimorecityschools.org", "title1", "open",
  "The city school district, with a high proportion of Title I schools.",
  "Go through the district's partnership office rather than individual schools; they route offers properly."),
 ("Montgomery County Public Schools", "Rockville", "Montgomery County", "https://www.montgomeryschoolsmd.org", "middle", "open",
  "One of the largest districts in the country, with an established partnership process.",
  "Use the district's partnership process. Individual schools will refer you to it anyway."),
 ("Prince George's County Public Schools", "Upper Marlboro", "Prince George's County", "https://www.pgcps.org", "title1", "open",
  "A large district with substantial Title I enrolment.",
  "Contact the district's family and community engagement office about school events."),
 ("Baltimore County Public Schools", "Towson", "Baltimore County", "https://www.bcps.org", "middle", "open",
  "The county district, covering a wide mix of urban and rural schools.",
  "Contact the STEM office at district level; they know which schools want visitors."),
 ("Anne Arundel County Public Schools", "Annapolis", "Anne Arundel County", "https://www.aacps.org", "middle", "open",
  "The county district serving Annapolis and surrounds.",
  "Ask the district STEM office which middle schools have no robotics offering."),
 ("Howard County Public School System", "Ellicott City", "Howard County", "https://www.hcpss.org", "middle", "open",
  "The county district, with strong existing STEM provision.",
  "Many schools here already have teams; ask instead which elementary schools want feeder programmes."),
 ("Frederick County Public Schools", "Frederick", "Frederick County", "https://education.fcps.org", "middle", "open",
  "The county district, covering both town and rural schools.",
  "Ask about their rural elementary schools, which get the fewest visits."),
]
